version: 2

jobs:
    test:
        docker:
          - image: circleci/python:3.8
        steps:
          - checkout
          - run: pip install -r requirements.txt && pytest -vvvv --mypy --flake8 tests

    try-setup-install:
        docker:
          - image: circleci/python:3.8
        steps:
          - checkout
          - run: |
              python3 -m virtualenv -p python3 env
              . env/bin/activate
              python setup.py install

workflows:
    version: 2
    build_and_test:
        jobs:
            - test
            - try-setup-install
