version: 2

jobs:
    test:
        docker:
          - image: circleci/python:latest
        steps:
          - checkout
          - run: |
              pip install --upgrade pip
              pip install -r requirements.txt -r requirements-dev.txt
              pytest -vvvv --mypy --flake8 tests

workflows:
    version: 2
    build_and_test:
        jobs:
            - test
