name: Check Dependencies

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Check requirements
      run: |
        (test -f requirements.txt && python tools/check-requirements.py requirements.txt) || echo "Skipping requirements.txt"
        (test -f requirements-dev.txt && python tools/check-requirements.py requirements-dev.txt) || echo "Skipping requirements-dev.txt"
