# For most recent version see:
# https://github.com/WIPACrepo/wipac-dev-tools/blob/main/.github/workflows/setup-and-release.yml
# Copy any updates to wipac-dev-tools.

name: Setup and Release

on: [push]

jobs:

  build-setup:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build setup.cfg
        run: |
          pip3 install requests
          echo $GITHUB_REPOSITORY
          python3 wipac_dev_tools/setup_builder.py setup.cfg $GITHUB_REPOSITORY

      - name: Build requirements.txt
        run: |
          echo "TBD"

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          if [ -z "$(git status --porcelain)" ]; then
            exit 0
          fi
          git commit -m "<bot> update setup.cfg and/or requirements.txt"
          git push
          exit 1  # prevent dependent job(s) since there's changes to the code

  release:
    needs: build-setup
    runs-on: ubuntu-latest
    concurrency: release

    steps:
    - uses: actions/checkout@v2
      if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
      with:
        fetch-depth: 0

    - name: Python Semantic Release
      if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
      uses: relekang/python-semantic-release@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        repository_username: __token__
        repository_password: ${{ secrets.PYPI_TOKEN }}