# For most recent version see:
# https://github.com/WIPACrepo/wipac-dev-tools/blob/main/.github/workflows/try-setup-install.yml
# Copy any updates to wipac-dev-tools.

name: Try Setup Install

on: [push]

jobs:

  gather-py3-versions:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.versions.outputs.matrix }}
    steps:
      - uses: actions/checkout@v2
      - id: versions
        uses: WIPACrepo/wipac-dev-py-versions-action@main

  pip-install:
    needs: gather-py3-versions
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix: ${{ fromJSON(needs.gather-py3-versions.outputs.matrix) }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py3_versions }}
      - run: |
          pip install --upgrade pip wheel setuptools
          pip install .
